apiVersion: v1
kind: Service
metadata:
  name: mydockservice-entrypoint
  namespace: mydock
spec:
  type: NodePort
  selector:
    bb: myservice
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002